package com.loanorigination.common.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Schema(description = "Rule configuration for credit decisioning")
public class RuleConfigurationDTO {
    
    @Schema(description = "Rule configuration ID", example = "1")
    private Long id;
    
    @NotBlank(message = "Rule name is required")
    @Schema(description = "Unique rule name", example = "MINIMUM_CREDIT_SCORE", required = true)
    private String ruleName;
    
    @NotBlank(message = "Rule type is required")
    @Schema(description = "Type of rule", example = "CREDIT_SCORE", allowableValues = {"CREDIT_SCORE", "LOAN_AMOUNT", "BUREAU_RESPONSE", "AGE_LIMIT"}, required = true)
    private String ruleType;
    
    @NotBlank(message = "Description is required")
    @Schema(description = "Human-readable description of the rule", example = "Credit score must be at least 650", required = true)
    private String description;
    
    @NotNull(message = "Threshold value is required")
    @Schema(description = "Threshold value for the rule", example = "650.00", required = true)
    private BigDecimal thresholdValue;
    
    @NotBlank(message = "Operator is required")
    @Schema(description = "Comparison operator", example = ">=", allowableValues = {">=", "<=", "==", ">", "<"}, required = true)
    private String operator;
    
    @Schema(description = "Whether the rule is enabled", example = "true")
    private Boolean enabled = true;
    
    @Schema(description = "Priority of the rule (lower number = higher priority)", example = "1")
    private Integer priority = 1;
    
    @Schema(description = "Importance level", example = "CRITICAL", allowableValues = {"CRITICAL", "HIGH", "MEDIUM", "LOW"})
    private String importance = "CRITICAL";
    
    @Schema(description = "Custom failure message when rule fails", example = "Credit score below minimum threshold")
    private String failureMessage;
    
    @Schema(description = "Origin of the rule", example = "MANUAL", allowableValues = {"MANUAL", "MODEL"})
    private String source = "MANUAL";
    
    @Schema(description = "Model confidence score for autogenerated rules", example = "0.85")
    private BigDecimal confidenceScore;
    
    @Schema(description = "Model version that generated the rule", example = "gpt-4-2024")
    private String modelVersion;
    
    @Schema(description = "Additional metadata for the rule in JSON format")
    private String metadata;
    
    @Schema(description = "Timestamp when rule was created")
    private LocalDateTime createdAt;
    
    @Schema(description = "Timestamp when rule was last updated")
    private LocalDateTime updatedAt;
    
    @Schema(description = "User who last updated the rule", example = "admin@example.com")
    private String updatedBy;
    
    // Explicit getters and setters
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getRuleName() {
        return ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }
    
    public String getRuleType() {
        return ruleType;
    }
    
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public BigDecimal getThresholdValue() {
        return thresholdValue;
    }
    
    public void setThresholdValue(BigDecimal thresholdValue) {
        this.thresholdValue = thresholdValue;
    }
    
    public String getOperator() {
        return operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    
    public Boolean getEnabled() {
        return enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    
    public Integer getPriority() {
        return priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    public String getImportance() {
        return importance;
    }
    
    public void setImportance(String importance) {
        this.importance = importance;
    }
    
    public String getFailureMessage() {
        return failureMessage;
    }
    
    public void setFailureMessage(String failureMessage) {
        this.failureMessage = failureMessage;
    }
    
    public String getSource() {
        return source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    
    public BigDecimal getConfidenceScore() {
        return confidenceScore;
    }
    
    public void setConfidenceScore(BigDecimal confidenceScore) {
        this.confidenceScore = confidenceScore;
    }
    
    public String getModelVersion() {
        return modelVersion;
    }
    
    public void setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion;
    }
    
    public String getMetadata() {
        return metadata;
    }
    
    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }
    
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public String getUpdatedBy() {
        return updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
}

